version: '3.0' # specify docker-compose version

# Define the services/ containers to be run
services:
  reclamador-admin-dev:  # name of the first service
    container_name: reclamador-admin-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile # specify the directory of the Dockerfile
    environment:
      NODE_ENV: development
      ___PUBLIC_DSN___:
    ports:
      - "4200:4200" # specify port mapping
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
